---
- name: Set a fact about the Ansible python interpreter
  ansible.builtin.set_fact:
    old_ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python' + ansible_facts.python.version.major | string) }}"

- ansible.builtin.import_tasks: images.yml
  when: os_images_build | bool

- ansible.builtin.import_tasks: upload.yml
  vars:
    ansible_python_interpreter: "{{ os_images_venv ~ '/bin/python' if os_images_venv != None else old_ansible_python_interpreter }}"
  when: os_images_upload | bool

- ansible.builtin.import_tasks: promote.yml
  vars:
    ansible_python_interpreter: "{{ os_images_venv ~ '/bin/python' if os_images_venv != None else old_ansible_python_interpreter }}"
  when: os_images_promote | bool
