---
- name: Set a fact about the Ansible python interpreter
  ansible.builtin.set_fact:
    old_ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python3') }}"

- name: Import task volumes.yml
  ansible.builtin.import_tasks: volumes.yml
  vars:
    ansible_python_interpreter: "{{ os_volumes_venv ~ '/bin/python' if os_volumes_venv != None else old_ansible_python_interpreter }}"
